classDiagram
    class Produto {
        - int id
        - string nome
        - int quantidade
        - decimal valor
        - string unidadeMedida
        - string categoria

        + void Cadastrar()
        + bool ValidarDados()
        + void Editar()
        + void Excluir()
        + string Visualizar()
    }
