graph TD
    F[Funcionário] --> A[Acessar opção Consultar Produto]
    A --> B[Exibir campos de filtro]
    B --> C[Funcionário define filtros e solicita busca]
    C --> D[Sistema exibe lista de produtos filtrados]
